@startuml
autonumber "<b>[###]"
title
 Ref: US4 
end title

participant  MobileApp as app

box "Backend Server" #LightBlue
    participant PostingService as post
    database PostingDB as postDB
end box

activate app
app -> post:  GET /api/v1/posts/{post_id}?lat={myLat}&long={myLong}
activate post
post -> postDB: <SELECT * FROM post WHERE id=<post_id>>
post -> post: validate post location

alt exists error
    post --> app: Status 4XX/5XX
else
    post --> app: Status 200 (Post)
end

@enduml